# Generated by Django 6.0.1 on 2026-01-13 22:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.chat'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(5000)]),
        ),
    ]
